### ISSUE TITLE
Persian Hershey Font

### ISSUE THREAD

**Issue by mkeyno** [sunzx/hershey#1]
hi , sorry to open ticket for my question , do you know instruction or software to convert Persian fonts to Hershey fonts?

**Comment by sunzx** [comment]
There is a Hershey font editor written in Java at http://www.batbox.org/editor/editfont.html . However, Persian letters which have different forms at different positions in a word need special considerations when rendering.

Format of the original .jhf font file can be found at https://www.ghostscript.com/doc/current/Hershey.htm . Some additional resources can be found at https://ctan.org/tex-archive/fonts/hershey?lang=en .
